services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      bash -c '
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:create &&
        bundle exec rails db:migrate &&
        bundle exec rails db:seed &&
        bundle exec rails s -b 0.0.0.0 -p 3000
      '
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgres://postgres:postgres@db:5432/graphql_template_development
      - REDIS_CACHE_URL=redis://redis:6379/0
      - REDIS_SIDEKIQ_URL=redis://redis:6379/1
      - REDIS_CABLE_URL=redis://redis:6379/2
      - SECRET_KEY_BASE=1d5248b6d7e9bcbdd706593c90a1fb3a7de5502b462e5a1f123e899ca75addee2d030c46759769076ace8af5c221634cc966406862a59d0748eb8d3bda20b275
    volumes:
      - .:/rails
      - /rails/tmp
    depends_on:
      - db
      - redis
      - sidekiq

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      bash -c '
        bundle exec sidekiq
      '
    environment:
      - RAILS_ENV=development
      - REDIS_SIDEKIQ_URL=redis://redis:6379/1
    volumes:
      - .:/rails
    depends_on:
      - redis
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graphql_template_development
    ports:
      - "5433:5432"
    volumes:
      - graphql_template_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - "6380:6379"

volumes:
  graphql_template_pgdata:
