common: &defaults
  monitor: <%= ENV["SCOUT_KEY"].present? %>
  log_level: debug
  key: <%= ENV["SCOUT_KEY"].present? %>
  name: <%= ENV["SCOUT_NAME"].presence || "GraphqlTemplate" %>

production:
  <<: *defaults

development:
  <<: *defaults
  monitor: true

test:
  <<: *defaults
  monitor: false

staging:
  <<: *defaults
